-- Main Table to store Features
CREATE TABLE FF4J_FEATURES (
  "FEAT_UID"        VARCHAR(100),
  "ENABLE"          INTEGER NOT NULL,
  "DESCRIPTION"     VARCHAR(1000),
  "STRATEGY"        VARCHAR(1000),
  "EXPRESSION"      VARCHAR(255),
  "GROUPNAME"       VARCHAR(100),
  PRIMARY KEY("FEAT_UID")
);

-- Roles to store ACL, FK to main table
CREATE TABLE FF4J_ROLES (
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
  "ROLE_NAME"    VARCHAR(100),
  PRIMARY KEY("FEAT_UID", "ROLE_NAME")
);

CREATE TABLE FF4J_CUSTOM_PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ"        VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"  VARCHAR(1000),
  "DESCRIPTION"  VARCHAR(1000),
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
  PRIMARY KEY("PROPERTY_ID", "FEAT_UID")
);